
version: "3"
   
services:
    frontend:
        build: ./frontend
        container_name: frontend
        ports:
          - 3000:80
        depends_on: 
          - backend  

    backend:
        build: ./backend
        container_name: backend
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
       

        
